### ISSUE TITLE
Review normalize.css 6.0.0

### ISSUE THREAD

**Issue by niksy** [niksy/rationalize.css#21]
* https://github.com/necolas/normalize.css/commit/91f668be643185dd7b08f122ccee0df711d237c0
* https://github.com/necolas/normalize.css/issues/664#issuecomment-292561959
* https://github.com/necolas/normalize.css/issues/664#issuecomment-291546434
* Use https://github.com/adamgruber/opinionate.css

**Comment by jonathantneal** [comment]
^ Definitely looks like you may want to add some of these rules into your project. Looks good, btw! 😄
